In [1]:
# load the iris dataset
from sklearn.datasets import load_iris
iris = load_iris()

In [2]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [3]:
load_iris()

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [4]:
# store the feature matrix (X) and response vector (y)
X = iris.data
Y = iris.target

In [5]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [13]:
Y
#Setosa = 0
#Versicolor= 1
#Virginica= 2

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [14]:
# splitting X and y into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=1)

In [15]:
#Total no. of obs in the data is 150
print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)

(120, 4)
(30, 4)
(120,)
(30,)


In [16]:
# training the model on training set
from sklearn.metrics import confusion_matrix
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train, Y_train)

GaussianNB()

In [17]:
y_pred_train = gnb.predict(X_train)
y_pred_train

array([1, 2, 1, 2, 2, 0, 1, 0, 1, 2, 2, 0, 1, 2, 1, 2, 0, 0, 0, 1, 0, 0,
       2, 2, 2, 2, 2, 1, 2, 1, 0, 2, 2, 0, 0, 2, 0, 2, 2, 1, 1, 2, 2, 0,
       1, 1, 2, 1, 2, 1, 0, 0, 0, 2, 0, 2, 2, 2, 0, 0, 1, 0, 2, 1, 2, 2,
       1, 2, 2, 1, 0, 1, 0, 1, 2, 0, 1, 0, 0, 2, 2, 2, 0, 0, 2, 0, 2, 0,
       2, 1, 0, 2, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 2, 0,
       0, 2, 1, 2, 1, 1, 2, 1, 2, 0])

In [19]:
from sklearn import metrics
print("Gaussian Naive Bayes model accuracy(in %):", metrics.accuracy_score(Y_train, y_pred_train))
print("Gaussian Naive Bayes model accuracy(in %):", metrics.accuracy_score(Y_train, y_pred_train)*100)

Gaussian Naive Bayes model accuracy(in %): 0.95
Gaussian Naive Bayes model accuracy(in %): 95.0


In [20]:
cm=confusion_matrix(Y_train, y_pred_train)
cm

array([[39,  0,  0],
       [ 0, 34,  3],
       [ 0,  3, 41]], dtype=int64)

In [33]:
import pandas as pd
Comparison_Train=pd.DataFrame(X_train)
Comparison_Train['Train_Actual']=pd.Series(Y_train,)
Comparison_Train['Train_Predict']=pd.Series(y_pred_train)
Comparison_Train
Comparison_Train[Comparison_Train['Train_Actual']!=Comparison_Train['Train_Predict']]

0    1    2    3  Train_Actual  Train_Predict
12   6.0  2.2  5.0  1.5             2              1
55   6.0  2.7  5.1  1.6             1              2
74   6.9  3.1  4.9  1.5             1              2
84   5.9  3.2  4.8  1.8             1              2
89   4.9  2.5  4.5  1.7             2              1
115  6.3  2.8  5.1  1.5             2              1

In [22]:
# making predictions on the testing set
y_pred_test = gnb.predict(X_test)

In [23]:
y_pred_test

array([0, 1, 1, 0, 2, 1, 2, 0, 0, 2, 1, 0, 2, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       2, 0, 2, 1, 0, 0, 1, 2])

In [24]:
# comparing actual response values (y_test) with predicted response values (y_pred)
from sklearn import metrics
print("Gaussian Naive Bayes model accuracy(in %):", metrics.accuracy_score(Y_test, y_pred_test)*100)

Gaussian Naive Bayes model accuracy(in %): 96.66666666666667


In [25]:
cm=confusion_matrix(Y_test, y_pred_test)
cm

array([[11,  0,  0],
       [ 0, 12,  1],
       [ 0,  0,  6]], dtype=int64)

In [34]:
import pandas as pd
Comparison_Test=pd.DataFrame(X_test)
Comparison_Test['Test_Actual']=pd.Series(Y_test)
Comparison_Test['Test_Predict']=pd.Series(y_pred_test)
Comparison_Test
Comparison_Test[Comparison_Test['Test_Actual']!=Comparison_Test['Test_Predict']]

0    1    2    3  Test_Actual  Test_Predict
22  6.7  3.0  5.0  1.7            1             2

# Naive Bayes on Categorical Data

In [41]:
from sklearn.naive_bayes import CategoricalNB
clf = CategoricalNB()

In [42]:
import pandas as pd
NB=pd.read_csv('D:\\ALL DATA SCIENCE\\Learn Digital\\DataSets\\NB.csv')
NB

Outlook Temperature Humidity Windy Play
0      Sunny         Hot     High    No   No
1      Sunny         Hot     High   Yes   No
2   Overcast         Hot     High    No  Yes
3      Rainy        Mild     High    No  Yes
4      Rainy        Cool   Normal    No  Yes
5      Rainy        Cool   Normal   Yes   No
6   Overcast        Cool   Normal   Yes  Yes
7      Sunny        Mild     High    No   No
8      Sunny        Cool   Normal    No  Yes
9      Rainy        Mild   Normal    No  Yes
10     Sunny        Mild   Normal   Yes  Yes
11  Overcast        Mild     High   Yes  Yes
12  Overcast         Hot   Normal    No  Yes
13     Rainy        Mild     High   Yes   No

In [43]:
NB_label=NB.copy()
NB_label.head()

Outlook Temperature Humidity Windy Play
0     Sunny         Hot     High    No   No
1     Sunny         Hot     High   Yes   No
2  Overcast         Hot     High    No  Yes
3     Rainy        Mild     High    No  Yes
4     Rainy        Cool   Normal    No  Yes

In [44]:
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
NB_label.iloc[:, -1] = labelencoder.fit_transform(NB_label.iloc[:,-1])
NB_label.iloc[:, 0] = labelencoder.fit_transform(NB_label.iloc[:,0])
NB_label.iloc[:, 1] = labelencoder.fit_transform(NB_label.iloc[:,1])
NB_label.iloc[:, 2] = labelencoder.fit_transform(NB_label.iloc[:,2])
NB_label.iloc[:, 3] = labelencoder.fit_transform(NB_label.iloc[:,3])

In [45]:
NB_label
#Outlook:  Sunny=2, Overcast=0, Rainy=1
#Temperature: Hot=1, Mild=2, Cool=0
#Humidity: High=0, Normal=1
#Windy: Yes=1, No=0
#Play= Yes=1, No=0

Outlook  Temperature  Humidity  Windy  Play
0         2            1         0      0     0
1         2            1         0      1     0
2         0            1         0      0     1
3         1            2         0      0     1
4         1            0         1      0     1
5         1            0         1      1     0
6         0            0         1      1     1
7         2            2         0      0     0
8         2            0         1      0     1
9         1            2         1      0     1
10        2            2         1      1     1
11        0            2         0      1     1
12        0            1         1      0     1
13        1            2         0      1     0

In [46]:
X=NB_label.iloc[:,:-1]
Y=NB_label.iloc[:,-1]

In [47]:
clf.fit(X, Y)

CategoricalNB()

In [48]:
#Calculate prediction for Outlook=Sunny,Temperature=Cool,Humidity=High,& Windy=Yes
import numpy as np
X_test=np.array([[2,0,0,1]])
#X_test.shape
#X_test.reshape(1, -1)

In [49]:
print(clf.predict(X_test))

[0]


In [50]:
# splitting X and y into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=1)

In [51]:
#Total no. of obs in the data is 14
print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)

(11, 4)
(3, 4)
(11,)
(3,)


In [52]:
clf.fit(X_train, Y_train)

CategoricalNB()

In [53]:
y_pred_train = clf.predict(X_train)
y_pred_train

array([1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1])

In [54]:
cm=confusion_matrix(Y_train, y_pred_train)
cm

array([[3, 1],
       [0, 7]], dtype=int64)

In [56]:
from sklearn import metrics
metrics.accuracy_score(Y_train, y_pred_train)*100

90.9090909090909

In [58]:
# making predictions on the testing set
y_pred_test = clf.predict(X_test)
y_pred_test

array([1, 1, 1])

In [59]:
# comparing actual response values (y_test) with predicted response values (y_pred)
from sklearn import metrics
metrics.accuracy_score(Y_test, y_pred_test)*100

66.66666666666666

In [60]:
cm=confusion_matrix(Y_test, y_pred_test)
cm

array([[0, 1],
       [0, 2]], dtype=int64)