In [2]:
import pandas as pd
from pandas import read_csv
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn import svm
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split, cross_val_score

SVM - pima-indians-diabetes

In [13]:
from pandas import read_csv
filename = 'F:\\Data Science\\Data Sets\\pima-indians-diabetes.csv';
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
dataframe = read_csv(filename, names = names)
dataframe = dataframe.iloc[1:,:]
dataframe

preg plas pres skin test  mass   pedi age class
1      6  148   72   35    0  33.6  0.627  50     1
2      1   85   66   29    0  26.6  0.351  31     0
3      8  183   64    0    0  23.3  0.672  32     1
4      1   89   66   23   94  28.1  0.167  21     0
5      0  137   40   35  168  43.1  2.288  33     1
..   ...  ...  ...  ...  ...   ...    ...  ..   ...
764   10  101   76   48  180  32.9  0.171  63     0
765    2  122   70   27    0  36.8   0.34  27     0
766    5  121   72   23  112  26.2  0.245  30     0
767    1  126   60    0    0  30.1  0.349  47     1
768    1   93   70   31    0  30.4  0.315  23     0

[768 rows x 9 columns]

In [14]:
X = dataframe.iloc[:, 0:8]
Y = dataframe.iloc[:,8]

In [15]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.3)

In [16]:
X_train.shape, Y_train.shape, X_test.shape, Y_test.shape


((537, 8), (537,), (231, 8), (231,))

In [17]:
#GRIDSEARCHCV
clf = SVC()
param_grid = [{'kernel' : ['rbf'], 'gamma' : [1, 0.1, 0.01, 0.001, 0.0001], 'C' : [0.1, 1, 10, 100, 1000]}]
gsv = GridSearchCV(clf, param_grid, refit = True, verbose = 3)
gsv.fit(X_train, Y_train)

Fitting 5 folds for each of 25 candidates, totalling 125 fits
[CV 1/5] END .....................C=0.1, gamma=1, kernel=rbf; total time=   0.0s
[CV 2/5] END .....................C=0.1, gamma=1, kernel=rbf; total time=   0.0s
[CV 3/5] END .....................C=0.1, gamma=1, kernel=rbf; total time=   0.0s
[CV 4/5] END .....................C=0.1, gamma=1, kernel=rbf; total time=   0.0s
[CV 5/5] END .....................C=0.1, gamma=1, kernel=rbf; total time=   0.0s
[CV 1/5] END ...................C=0.1, gamma=0.1, kernel=rbf; total time=   0.0s
[CV 2/5] END ...................C=0.1, gamma=0.1, kernel=rbf; total time=   0.0s
[CV 3/5] END ...................C=0.1, gamma=0.1, kernel=rbf; total time=   0.0s
[CV 4/5] END ...................C=0.1, gamma=0.1, kernel=rbf; total time=   0.0s
[CV 5/5] END ...................C=0.1, gamma=0.1, kernel=rbf; total time=   0.0s
[CV 1/5] END ..................C=0.1, gamma=0.01, kernel=rbf; total time=   0.0s
[CV 2/5] END ..................C=0.1, gamma=0.0

[CV 2/5] END ....................C=1000, gamma=1, kernel=rbf; total time=   0.0s
[CV 3/5] END ....................C=1000, gamma=1, kernel=rbf; total time=   0.0s
[CV 4/5] END ....................C=1000, gamma=1, kernel=rbf; total time=   0.0s
[CV 5/5] END ....................C=1000, gamma=1, kernel=rbf; total time=   0.0s
[CV 1/5] END ..................C=1000, gamma=0.1, kernel=rbf; total time=   0.0s
[CV 2/5] END ..................C=1000, gamma=0.1, kernel=rbf; total time=   0.0s
[CV 3/5] END ..................C=1000, gamma=0.1, kernel=rbf; total time=   0.0s
[CV 4/5] END ..................C=1000, gamma=0.1, kernel=rbf; total time=   0.0s
[CV 5/5] END ..................C=1000, gamma=0.1, kernel=rbf; total time=   0.0s
[CV 1/5] END .................C=1000, gamma=0.01, kernel=rbf; total time=   0.0s
[CV 2/5] END .................C=1000, gamma=0.01, kernel=rbf; total time=   0.0s
[CV 3/5] END .................C=1000, gamma=0.01, kernel=rbf; total time=   0.0s
[CV 4/5] END ...............

GridSearchCV(estimator=SVC(),
             param_grid=[{'C': [0.1, 1, 10, 100, 1000],
                          'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                          'kernel': ['rbf']}],
             verbose=3)

In [18]:
gsv.best_params_, gsv.best_score_

({'C': 10, 'gamma': 0.0001, 'kernel': 'rbf'}, 0.7746452059536171)

In [19]:
clf = SVC(C = 12, gamma = 0.1)
clf.fit(X_train, Y_train)
y_pred_train = clf.predict(X_train)
y_pred_train

array(['1', '1', '1', '0', '1', '1', '1', '0', '1', '1', '0', '0', '0',
       '0', '1', '1', '1', '0', '1', '0', '0', '1', '1', '0', '0', '0',
       '0', '0', '0', '1', '0', '0', '1', '0', '0', '1', '1', '1', '0',
       '0', '1', '0', '0', '1', '0', '0', '0', '0', '0', '1', '0', '0',
       '0', '1', '0', '1', '1', '0', '0', '0', '0', '0', '0', '0', '0',
       '1', '0', '0', '0', '0', '0', '0', '1', '0', '1', '0', '0', '0',
       '0', '1', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0',
       '0', '1', '0', '0', '0', '0', '1', '1', '0', '0', '0', '1', '1',
       '1', '0', '0', '1', '1', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '1', '1', '0', '1', '0', '0', '1', '1', '0', '1', '1',
       '1', '0', '0', '0', '1', '1', '0', '0', '0', '0', '0', '1', '0',
       '0', '0', '1', '0', '0', '0', '1', '0', '0', '0', '0', '1', '0',
       '1', '1', '1', '0', '0', '0', '0', '0', '0', '1', '0', '0', '1',
       '0', '0', '0', '0', '0', '0', '1', '1', '0', '0', '0', '0

In [20]:
acc = accuracy_score(Y_train, y_pred_train) * 100
acc

100.0

In [21]:
confusion_matrix(Y_train, y_pred_train)

array([[358,   0],
       [  0, 179]], dtype=int64)

In [22]:
y_pred_test = clf.predict(X_test)
y_pred_test
acc = accuracy_score(Y_test, y_pred_test) * 100
print("Accuracy = ", acc)
confusion_matrix(Y_test, y_pred_test)

Accuracy =  61.471861471861466


array([[142,   0],
       [ 89,   0]], dtype=int64)

In [23]:
y_pred_test

array(['0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0

IRIS DATASET

In [24]:
from pandas import read_csv
dataframe = pd.read_csv('F:\\Data Science\\Data Sets\\iris.csv')
#names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
#dataframe = read_csv(filename, names = names)
#dataframe = dataframe.iloc[1:,:]
dataframe

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [25]:
X = dataframe.iloc[:, 0:4]
Y = dataframe.iloc[:,4]

In [ ]:
X

In [ ]:
Y

In [26]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.3)

In [27]:
X_train.shape, Y_train.shape, X_test.shape, Y_test.shape

((105, 4), (105,), (45, 4), (45,))

In [28]:
clf = SVC()
param_grid = [{'kernel' : ['poly'], 'gamma' : [100, 50, 0.5, 0.1, 0.01], 'C' : [15, 14, 13, 12, 0.001, 0.0001]}]
gsv = GridSearchCV(clf, param_grid)
gsv.fit(X_train, Y_train)

GridSearchCV(estimator=SVC(),
             param_grid=[{'C': [15, 14, 13, 12, 0.001, 0.0001],
                          'gamma': [100, 50, 0.5, 0.1, 0.01],
                          'kernel': ['poly']}])

In [29]:
gsv.best_params_, gsv.best_score_

({'C': 15, 'gamma': 0.5, 'kernel': 'poly'}, 0.9523809523809523)

In [30]:
clf = SVC(C = 15, gamma = 0.5)
clf.fit(X_train, Y_train)
y_pred_train = clf.predict(X_train)
y_pred_train


array(['versicolor', 'versicolor', 'versicolor', 'virginica', 'virginica',
       'setosa', 'setosa', 'setosa', 'setosa', 'versicolor', 'setosa',
       'setosa', 'virginica', 'virginica', 'virginica', 'setosa',
       'virginica', 'virginica', 'setosa', 'virginica', 'virginica',
       'setosa', 'versicolor', 'virginica', 'setosa', 'virginica',
       'versicolor', 'virginica', 'setosa', 'setosa', 'versicolor',
       'versicolor', 'versicolor', 'virginica', 'versicolor', 'virginica',
       'virginica', 'virginica', 'versicolor', 'setosa', 'setosa',
       'setosa', 'setosa', 'virginica', 'setosa', 'setosa', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'virginica', 'virginica', 'virginica', 'versicolor', 'versicolor',
       'virginica', 'setosa', 'virginica', 'versicolor', 'virginica',
       'setosa', 'setosa', 'virginica', 'setosa', 'versicolor', 'setosa',
       'versicolor', 'virginica', 'virginica', 'versicolor', 'setosa',
       'setosa',

In [31]:
acc = accuracy_score(Y_train, y_pred_train) * 100
acc

97.14285714285714

In [32]:
confusion_matrix(Y_train, y_pred_train)

array([[37,  0,  0],
       [ 0, 33,  2],
       [ 0,  1, 32]], dtype=int64)

In [33]:
y_pred_test = clf.predict(X_test)
y_pred_test
acc = accuracy_score(Y_test, y_pred_test) * 100
print("Accuracy = ", acc)
confusion_matrix(Y_test, y_pred_test)

Accuracy =  95.55555555555556


array([[13,  0,  0],
       [ 0, 15,  0],
       [ 0,  2, 15]], dtype=int64)

In [ ]:
y_pred_test

SVM - CLAIMANTS DATA SET

In [34]:
claimants= pd.read_csv('F:\\Data Science\\Data Sets\\claimants.csv')
claimants

CASENUM  ATTORNEY  CLMSEX  CLMINSUR  SEATBELT  CLMAGE    LOSS
0           5         0     0.0       1.0       0.0    50.0  34.940
1           3         1     1.0       0.0       0.0    18.0   0.891
2          66         1     0.0       1.0       0.0     5.0   0.330
3          70         0     0.0       1.0       1.0    31.0   0.037
4          96         1     0.0       1.0       0.0    30.0   0.038
...       ...       ...     ...       ...       ...     ...     ...
1335    34100         1     0.0       1.0       0.0     NaN   0.576
1336    34110         0     1.0       1.0       0.0    46.0   3.705
1337    34113         1     1.0       1.0       0.0    39.0   0.099
1338    34145         0     1.0       0.0       0.0     8.0   3.177
1339    34153         1     1.0       1.0       0.0    30.0   0.688

[1340 rows x 7 columns]

In [35]:
claimants.isnull().sum()

CASENUM       0
ATTORNEY      0
CLMSEX       12
CLMINSUR     41
SEATBELT     48
CLMAGE      189
LOSS          0
dtype: int64

In [36]:
# Removing NA values in data set
claimants = claimants.dropna()
claimants.shape

(1096, 7)

In [37]:
X=claimants.iloc[:,2:]
Y=claimants['ATTORNEY']

In [38]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.2)
X_train.shape, Y_train.shape, X_test.shape, Y_test.shape

((876, 5), (876,), (220, 5), (220,))

In [39]:
clf = SVC()
#param_grid = [{'kernel':['poly'],'gamma':[1, 0.1, 0.01, 0.001, 0.0001],'C':[0.1, 1, 10, 100, 1000]}]
param_grid = [{'kernel':['rbf'],'gamma':[1, 0.1, 0.01, 0.001, 0.0001],'C':[0.1, 1, 10, 100, 1000]}]
gsv = GridSearchCV(clf,param_grid,refit = True, verbose = 3)
gsv.fit(X_train,Y_train)

Fitting 5 folds for each of 25 candidates, totalling 125 fits
[CV 1/5] END .....................C=0.1, gamma=1, kernel=rbf; total time=   0.0s
[CV 2/5] END .....................C=0.1, gamma=1, kernel=rbf; total time=   0.0s
[CV 3/5] END .....................C=0.1, gamma=1, kernel=rbf; total time=   0.0s
[CV 4/5] END .....................C=0.1, gamma=1, kernel=rbf; total time=   0.0s
[CV 5/5] END .....................C=0.1, gamma=1, kernel=rbf; total time=   0.0s
[CV 1/5] END ...................C=0.1, gamma=0.1, kernel=rbf; total time=   0.0s
[CV 2/5] END ...................C=0.1, gamma=0.1, kernel=rbf; total time=   0.0s
[CV 3/5] END ...................C=0.1, gamma=0.1, kernel=rbf; total time=   0.0s
[CV 4/5] END ...................C=0.1, gamma=0.1, kernel=rbf; total time=   0.0s
[CV 5/5] END ...................C=0.1, gamma=0.1, kernel=rbf; total time=   0.0s
[CV 1/5] END ..................C=0.1, gamma=0.01, kernel=rbf; total time=   0.0s
[CV 2/5] END ..................C=0.1, gamma=0.0

[CV 4/5] END ....................C=1000, gamma=1, kernel=rbf; total time=   0.0s
[CV 5/5] END ....................C=1000, gamma=1, kernel=rbf; total time=   0.0s
[CV 1/5] END ..................C=1000, gamma=0.1, kernel=rbf; total time=   0.1s
[CV 2/5] END ..................C=1000, gamma=0.1, kernel=rbf; total time=   0.2s
[CV 3/5] END ..................C=1000, gamma=0.1, kernel=rbf; total time=   0.2s
[CV 4/5] END ..................C=1000, gamma=0.1, kernel=rbf; total time=   0.1s
[CV 5/5] END ..................C=1000, gamma=0.1, kernel=rbf; total time=   0.1s
[CV 1/5] END .................C=1000, gamma=0.01, kernel=rbf; total time=   0.1s
[CV 2/5] END .................C=1000, gamma=0.01, kernel=rbf; total time=   0.1s
[CV 3/5] END .................C=1000, gamma=0.01, kernel=rbf; total time=   0.0s
[CV 4/5] END .................C=1000, gamma=0.01, kernel=rbf; total time=   0.0s
[CV 5/5] END .................C=1000, gamma=0.01, kernel=rbf; total time=   0.1s
[CV 1/5] END ...............

GridSearchCV(estimator=SVC(),
             param_grid=[{'C': [0.1, 1, 10, 100, 1000],
                          'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                          'kernel': ['rbf']}],
             verbose=3)

In [40]:
gsv.best_params_ , gsv.best_score_ 

({'C': 10, 'gamma': 0.01, 'kernel': 'rbf'}, 0.7088831168831169)

In [41]:
clf = SVC(C= 10, gamma = 0.01)
clf.fit(X_train , Y_train)
y_pred_train = clf.predict(X_train)
acc = accuracy_score(Y_train, y_pred_train) * 100
print("Accuracy =", acc)
confusion_matrix(Y_train, y_pred_train)

Accuracy = 72.3744292237443


array([[303, 151],
       [ 91, 331]], dtype=int64)

In [42]:
y_pred_test = clf.predict(X_test)
acc = accuracy_score(Y_test, y_pred_test) * 100
print("Accuracy =", acc)
confusion_matrix(Y_test, y_pred_test)

Accuracy = 69.54545454545455


array([[79, 45],
       [22, 74]], dtype=int64)